Sprint 3
EkaHvo/middle.messenger.praktikum.yandex pull request #4
Opened 2022-10-02 18:22 UTC by EkaHvo

2022-10-02 19:42 UTC, podlovchenko requested changes
Привет)

На странице регистрации сейчас вызывается метод для авторизации, поэтому не получается зарегистрировать нового пользователя

2022-10-02 19:42 UTC, podlovchenko commented on .mocharc.json
> +}
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-10-02 19:42 UTC, podlovchenko commented on package.json
> +    "@types/chai": "^4.3.3",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-10-02 19:42 UTC, podlovchenko commented on src/components/avatar/index.ts
> +            src: this.props.src ? `https://ya-praktikum.tech/api/v2/resources${this.props.src}`: false,
Было бы отлично вынести url в константу

2022-10-02 19:42 UTC, podlovchenko commented on src/components/chatsList/index.ts
> +const withChats = withStore((state) => ({chats: [...(state.chats || [] )] }))
Почему не просто 
```suggestion
const withChats = withStore((state) => ({chats: state.chats || [] }))
```

2022-10-02 19:42 UTC, podlovchenko commented on src/components/friendInfoTopLine/index.ts
> +    selectedChatUsers: User[] | [];
Объединение с обычным массивом здесь не нужно

2022-10-02 19:42 UTC, podlovchenko commented on src/components/friendInfoTopLine/index.ts
> +    }
Если в конструкторе только вызов родительского, то можно не указывать

2022-10-02 19:42 UTC, podlovchenko commented on src/controllers/AuthController.ts
> +    }
Логирование ошибок можно внести внутрь http transport, чтобы не дублировать логику

2022-10-02 19:42 UTC, podlovchenko commented on src/pages/signin/index.ts
> +            AuthController.signin(data as SignupData);
Это страница регистрация, ее следует назвать signup и использовать соответствующий метод

2022-10-03 08:41 UTC, EkaHvo commented on src/controllers/AuthController.ts
> +    }
Большое спасибо за развернутое ревью и комментарии!!! Постараюсь все поправить. Логи хотела заменить временно алертами, для каждого контроллера чтобы был разный текст с информацией, что пошло не так для пользователя. Можно пока оставить так?

2022-10-03 15:21 UTC, podlovchenko commented on src/controllers/AuthController.ts
> +    }
Да, окей)

2022-10-03 15:21 UTC, podlovchenko commented
Сейчас сборка не запускается
<img width="695" alt="Снимок экрана 2022-10-03 в 18 21 01" src="https://user-images.githubusercontent.com/22602747/193614788-75a93862-3a46-49a1-abd6-74b6aa1140b3.png">

2022-10-03 19:09 UTC, podlovchenko commented
Все еще не запускается

2022-10-04 09:00 UTC, EkaHvo commented
У меня запуск проходит нормально. Добавила --no-cache  в скрипт, прошу перед сборкой удалить папки dist и .parcel-cache

2022-10-04 18:22 UTC, podlovchenko commented
Привет, собралось
Есть замечание, сейчас при обновлении страницы `Cannot GET /settings`
По заданию
<img width="708" alt="Снимок экрана 2022-10-04 в 21 22 27" src="https://user-images.githubusercontent.com/22602747/193896138-f1b68da4-75cf-4a2d-8b4b-3f50e1341649.png">

2022-10-05 09:42 UTC, EkaHvo commented
добавила express-history-api-fallback

2022-10-06 07:44 UTC, podlovchenko approved these changes
Привет, работу принимаю)

2022-10-06 07:44 UTC, podlovchenko commented on server.js
>  process.env.PORT || PORT;
`process.env.PORT || PORT` Сейчас никуда не присваивается
```suggestion
const PORT = process.env.PORT || 3000;
```

2022-10-06 07:44 UTC, podlovchenko commented on server.js
> +app.use(fallback('index.html', { root: root }));
```suggestion
app.use(fallback('index.html', { root }));
```
Можно еще через
```
app.get('*', (req, res) => {
  res.sendFile(__dirname + '/dist/');
});
```

2022-10-08 14:19 UTC, merged